apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
  - port: 27017
  selector:
    app: mongodb
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 2
  
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        env:
          # Use secret in real usage
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 27017
          name: mongodb
          #Volumes
        #volumeMounts:
        #- name: mysql-vol
        #  mountPath: /var/lib/mysql
      #volumes:
      #- name: mysql-vol
      #  persistentVolumeClaim:
      #    claimName: mysql-pv-claim