apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    run: mysqldb
spec:
  containers:
      - image: puckel/docker-airflow
        name: airflow
        env:
          - name: LOAD_EX
            value: t
  image: mysql
  name: mysqldb
  ports:
  - containerPort: 3306
    protocol: TCP
---