apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    run: mysqldb
spec:
  containers:
    - env:
    - name: MYSQL_ROOT_PASSWORD
        value: password
    image: mysql
    name: mysqldb
    ports:
    - containerPort: 3306
      protocol: TCP