apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    name: mysqldb
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 3306
    targetPort: 3306
    
apiVersion: v1
kind: Pod
metadata:
  name: mysqldb
  labels:
    name: mysqldb
spec:
  containers:
  - image: mysql
    name: mysqldb
    env:
      - name: MYSQL_ROOT_PASSWORD
          value: password

    command:
      - sleep
      - "10"