apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  selector:
    name: mysqldb
  type: NodePort
  ports:
  - name: foo # Actually, no port is needed.
    port: 3306
    targetPort: 3306
---
 apiVersion: v1
  kind: Pod
  metadata:
    labels:
      run: mysqldb
    name: mysqldb
    namespace: default
  spec:
    containers:
    - env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      image: mysql
      name: mysqldb
      ports:
      - containerPort: 3306
        protocol: TCP