
command_centos: yum search batatot
command_ubuntu: apt search kabukim
shell_command: yum install open-vm-tools -y;systemctl enable vmtoolsd;systemctl start vmtoolsd
script_centos: docker-base-centos.sh  
script_ubuntu: pwsh_install_ubuntu.sh
installer_centos: yum
installer_ubuntu: apt
installer_alpine: apk
src_path: get_hostname.j2
dest_path: /tmp/hostname.txt
handler_name: i_did_something_Here

#apps
apps: sudo,vim,passwd,net-tools,traceroute,mtr,
  telnet,tcpdump,lshw,tree,whois,python3,epel-release,bash-completion

apps_alpine: sudo,vim,net-tools,traceroute,mtr,
  tcpdump,lshw,tree,whois,python3,py3-pip,busybox,busybox-extras
  
app_state: present

#users (mkpasswd --method=sha-512)
ansible_user_pass:
 $6$0PM.iO/XN8X9fqlf$8wxitYp7jLaQd0KpfVmikYF9PJK14d.QyRADALcOzBDDYpawad8qsglFVdG43iTV1bonupk0n4MduDdgvrjAJ/
root_pass:
 $6$L1bP9AvWCcvksHG1$IGfTqyv3hZgESqmN8h5YyGZRb311OiLhOhmxDSvafh/phNleNY7PgHLn.22RbW1kj5JG/5tsar/JapEp/zvZu0
user_state: present