version: '3'
networks:
  zabbix-net:
    #external: true
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
    networks: 
      - zabbix-net
    ports:
      - 3306:3306
      
  zabbix-srv:
    image: zabbix/zabbix-server-mysql
    networks: 
      - zabbix-net
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1q2w3e4r
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql
    networks: 
      - zabbix-net
    ports: 
      - 88:8080
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1q2w3e4r
      - ZBX_SERVER_HOST=zabbix-srv
      - PHP_TZ=Asia/Jerusalem

# Docker Networks
#networks:
#  zabbix-net:
#    driver: bridge

