version: '3'
#networks:
#  zabbix-net:
#    external: true
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    #  - MYSQL_USER=zabbix
    #  - MYSQL_PASSWORD=zabbix
  #  networks: 
  #    - zabbix-net
    ports:
      - 3306:3306
    volumes: 
      - db-data:/var/lib/mysql

  zabbix-srv:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-srv
  #  networks: 
  #    - zabbix-net
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=mysql 
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix-web
  #  networks: 
  #    - zabbix-net
    ports: 
      - 88:8080
    environment: 
      - DB_SERVER_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - ZBX_SERVER_HOST=zabbix-srv
      - PHP_TZ=Asia/Jerusalem
      
volumes: 
  db-data:

# Docker Networks
#networks:
#  zabbix-net:
#    driver: bridge

