{
        "username": "root",
        "group_name":"centos",
        "script_centos": "./scripts/docker-base-centos.sh",
        "script_ubuntu": "./scripts/docker-base-ubuntu.sh",
        "installer_centos": "yum",
        "installer_ubuntu": "apt",
        "apps": "vim, net-tools, traceroute",
        "state": "present",
        "command": "ls -lah" 
}
