Vagrant.configure("2") do |config|
  config.vm.box = "centos7"
  config.vm.provider :hyperv do |hyperv|
    hyperv.memory = "2048"
    hyperv.vmname = "centos7"
    hyperv.cpus = "2"
  end

  config.vm.disk :disk, name: "SYSTEM", size: "50GB"
  #config.vm.disk :dvd, name: "installer", path: "./installer.iso"
  
  #NETWORK
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"

   
   config.vm.provision "shell", path: "https://raw.githubusercontent.com/avi-h/scripts/master/bash/vagrant/centos7-hyperv-base.sh"  
   
   #config.vm.provision "shell", inline: <<-SHELL
    #  yum update -y
    #  yum install bash-completion -y
    #  yum install bash-completion-extras -y
    # yum install net-tools -y
    #  yum install vim -y
    #  yum install tcpdump -y
    #  yum install docker -y
    #  yum install gnupg2 -y
    #  systemctl enable docker
    #  systemctl start docker
    #  systemctl stop firewalld
    #  systemctl disable firewalld
    #  hostnamectl set-hostname centos7
    #  curl https://packages.microsoft.com/config/rhel/7/prod.repo | sudo tee /etc/yum.repos.d/microsoft.repo
    #  sudo yum install -y powershell
    #  sudo sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config
    #  shutdown -r now
     
   #SHELL
end